/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#ifndef _Included_project_CubiomesBridge
#define _Included_project_CubiomesBridge
#ifdef __cplusplus
extern "C" {
#endif
JNIEXPORT jintArray JNICALL Java_project_CubiomesBridge_nativeGetHutInRegion
  (JNIEnv *, jclass, jlong, jint, jint, jint);

JNIEXPORT jintArray JNICALL Java_project_CubiomesBridge_nativeClimateRegion
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

JNIEXPORT jboolean JNICALL Java_project_CubiomesBridge_nativeClimateFilter
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
